apiVersion: v1
kind: Pod
metadata:
  name: busybox-security-demo
  labels:
    app: busybox-demo
spec:
  containers:
  - name: busybox-root
    image: busybox:latest
    command: ["sh", "-c", "echo 'Running as root user'; id; sleep 3600"]
    securityContext:
      runAsUser: 0  # Run as root (UID 0)
      runAsGroup: 0
  
  - name: busybox-nonroot
    image: busybox:latest
    command: ["sh", "-c", "echo 'Running as non-root user'; id; sleep 3600"]
    securityContext:
      runAsUser: 1000  # Run as non-root user (UID 1000)
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      runAsNonRoot: true  # Enforce non-root execution