pipeline {
    agent any
     environment {
        KUBECONFIG = "${env.USERPROFILE}\\.kube\\config"
        KUBECTL_CONTEXT = 'minikube'
        MINIKUBE_HOME = "C:\\Users\\prasad"
    }

    stages {
        stage('Check Helm') {
            steps {
                script {
                    sh '''
                        set +x
                        helm version
                        helmfile version
                        minikube update-context
                        minikube status
                        pwd
                        ls -ltrh
                        cd root-constraint
                        helmfile sync --skip-deps --wait 2>&1 | tee ${logFile} || DEPLOYMENT_FAILED=true
                        echo "Getting events in gk-test namespace"
                        kubectl get events --namespace gk-test
                    '''
                }
            }
        }
    }
}

