pipeline {
    agent any
     environment {
        KUBECONFIG = "${env.USERPROFILE}\\.kube\\config"
        KUBECTL_CONTEXT = 'minikube'
        MINIKUBE_HOME = "C:\\Users\\prasad"
    }

    stages {
        stage('Check Helm') {
            steps {
                sh '''
                    set +x
                    helm version
                    helmfile version
                    minikube update-context
                    minikube status
                    pwd
                    ls -ltrh
                    cd root-constraint
                    kubectl get namespace | grep -q "gk-test" || kubectl create namespace gk-test
                    helmfile sync --skip-deps --wait || DEPLOYMENT_FAILED=true
                    if [ "$DEPLOYMENT_FAILED" = true ]; then
                        echo "Helm deployment failed"
                        echo "Getting events in gk-test namespace"
                        sleep 5
                        kubectl get events --namespace gk-test
                    fi
                    echo "Getting events in gk-test namespace"
                    sleep 10
                    kubectl get events --namespace gk-test
                '''
            }
        }
    }
}
